name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android platform & tools
        run: |
          sdkmanager --install "platforms;android-34" "build-tools;34.0.0" "platform-tools"
          yes | sdkmanager --licenses

      - name: Create Android project
        run: |
          mkdir -p app/src/main/java/com/sinopec/xn app/src/main/res/{layout,values,xml,drawable,mipmap-anydpi-v26}

          cat > settings.gradle <<'EOF'
          rootProject.name = "SinopecXN_WebView"
          include(":app")
          EOF

          cat > build.gradle <<'EOF'
          buildscript {
            repositories { google(); mavenCentral() }
            dependencies { classpath "com.android.tools.build:gradle:8.5.2" }
          }
          allprojects { repositories { google(); mavenCentral() } }
          EOF

          cat > app/build.gradle <<'EOF'
          apply plugin: "com.android.application"
          android {
            namespace "com.sinopec.xn"
            compileSdkVersion 34
            defaultConfig {
              applicationId "com.sinopec.xn"
              minSdkVersion 24
              targetSdkVersion 34
              versionCode 1
              versionName "1.0"
            }
            buildTypes {
              debug { minifyEnabled false }
              release { minifyEnabled false }
            }
          }
          dependencies {
            implementation "androidx.appcompat:appcompat:1.7.0"
            implementation "com.google.android.material:material:1.12.0"
          }
          EOF

          cat > app/src/main/AndroidManifest.xml <<'EOF'
          <manifest xmlns:android="http://schemas.android.com/apk/res/android">
            <uses-permission android:name="android.permission.INTERNET"/>
            <application android:label="Sinopec XN" android:icon="@mipmap/ic_launcher">
              <activity android:name=".MainActivity" android:exported="true">
                <intent-filter>
                  <action android:name="android.intent.action.MAIN"/>
                  <category android:name="android.intent.category.LAUNCHER"/>
                </intent-filter>
              </activity>
            </application>
          </manifest>
          EOF

          cat > app/src/main/java/com/sinopec/xn/MainActivity.java <<'EOF'
          package com.sinopec.xn;
          import android.os.Bundle;
          import android.webkit.WebView;
          import androidx.appcompat.app.AppCompatActivity;
          public class MainActivity extends AppCompatActivity {
            @Override
            protected void onCreate(Bundle savedInstanceState) {
              super.onCreate(savedInstanceState);
              WebView w = new WebView(this);
              setContentView(w);
              w.getSettings().setJavaScriptEnabled(true);
              w.loadUrl("https://employeesxn.netlify.app/");
            }
          }
          EOF

      - name: Install Gradle 8.7
        run: |
          wget -q https://services.gradle.org/distributions/gradle-8.7-bin.zip -O /tmp/gradle.zip
          unzip -q /tmp/gradle.zip -d $HOME
          echo "$HOME/gradle-8.7/bin" >> $GITHUB_PATH

      - name: Build debug APK
        run: |
          gradle wrapper --gradle-version 8.7
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SinopecXN-APK
          path: app/build/outputs/apk/debug/app-debug.apk
