name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Unzip Android project
        run: unzip SinopecXN_WebView.zip -d project

      # Create a Gradle Wrapper inside the project (so builds are consistent)
      - name: Install Gradle and generate wrapper
        working-directory: project
        run: |
          sudo apt-get update
          sudo apt-get install -y gradle
          gradle --version
          gradle wrapper --gradle-version 8.7
          chmod +x ./gradlew

      # Build Debug APK (you can add assembleRelease later if you want)
      - name: Build APK
        working-directory: project
        run: ./gradlew --no-daemon assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: SinopecXN-APK
          path: |
            project/app/build/outputs/apk/debug/app-debug.apk
