name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Install Android commandline tools + accept licenses
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Unzip project
        run: unzip SinopecXN_WebView.zip -d project

      # Build even if there's no Gradle wrapper in the ZIP
      - name: Build APK (handles missing gradlew)
        working-directory: project
        run: |
          if [ -x ./gradlew ]; then
            chmod +x ./gradlew
            ./gradlew --no-daemon assembleDebug
          else
            sudo apt-get update
            sudo apt-get install -y gradle
            gradle --version
            gradle --no-daemon assembleDebug
          fi

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: SinopecXN-APK
          path: project/app/build/outputs/apk/debug/app-debug.apk
